Profiles:
  OrgsOrdererGenesis:
    Orderer:
      # Orderer Type: The orderer implementation to start
      # Available types are "solo" and "kafka"
      OrdererType: kafka
      Addresses:
        - orderer0-org0:7050
        - orderer1-org0:7050
        - orderer2-org0:7050

      # Batch Timeout: The amount of time to wait before creating a batch
      BatchTimeout: 2s

      # Batch Size: Controls the number of messages batched into a block
      BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

      Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
          - kafka0-org0:9092
          - kafka1-org0:9092
          - kafka2-org0:9092

      # Organizations is the list of orgs which are defined as participants on
      # the orderer side of the network
      Organizations:
        - *org0

    Consortiums:

      SampleConsortium:

        Organizations:
          - *org1

  OrgsChannel:
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *org1


Organizations:

  - &org0

    Name: org0

    # ID to load the MSP definition as
    ID: org0MSP

    # MSPDir is the filesystem path which contains the MSP configuration
    MSPDir: ./data/org0/ica-org0-admin/msp

  - &org1

    Name: org1

    # ID to load the MSP definition as
    ID: org1MSP

    # MSPDir is the filesystem path which contains the MSP configuration
    MSPDir: ./data/org1/ica-org1-admin/msp

    AnchorPeers:
       # AnchorPeers defines the location of peers which can be used
       # for cross org gossip communication.  Note, this value is only
       # encoded in the genesis block in the Application section context
       - Host: peer1-org1
         Port: 7051

Application: &ApplicationDefaults
    Organizations:
