version: '3.5'

networks:
  default:
    external:
      name: mynet

services:
      
  rcamariadb-org0:
    image: mariadb:10
    container_name: rcamariadb-org0
    hostname: rcamariadb-org0
    environment:
      - MYSQL_ROOT_PASSWORD=qawsedrf
    ports:
      - 3306:3306
    networks:
      default:
    restart: always

  rca-org0:
    image: hyperledger/fabric-ca:x86_64-1.1.0
    container_name: rca-org0
    hostname: rca-org0
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_CA_NAME=rca-org0
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=rca-org0
      - FABRIC_CA_SERVER_CSR_HOSTS=rca-org0
      - FABRIC_CA_SERVER_DEBUG=true
      - BOOTSTRAP_USER_PASS=rca-org0-admin:adminpw
      - TARGET_CERTFILE=/data/org0-ca-cert.pem
      - FABRIC_ORGS=org0 org1
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=mynet
      - MYSQL_SERVER_NAME = rcamariadb-org0
    ports:
      - 7054:7054
    command: /bin/bash -c '/scripts/start-rca-org0.sh'
    depends_on:
      - rcamariadb-org0
    volumes:
      - ./scripts:/scripts
      - ./data:/data
    networks: 
      default:
    restart: always

  icamariadb-org0:
    image: mariadb:10
    container_name: icamariadb-org0
    hostname: icamariadb-org0
    environment:
      - MYSQL_ROOT_PASSWORD=qawsedrf
    ports:
      - 3307:3306
    networks:
      default:
    restart: always

  ica-org0:
    image: hyperledger/fabric-ca:x86_64-1.1.0
    container_name: ica-org0
    hostname: ica-org0
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_CA_NAME=ica-org0
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=ica-org0
      - FABRIC_CA_SERVER_CSR_HOSTS=ica-org0
      - FABRIC_CA_SERVER_INTERMEDIATE_TLS_CERTFILES=/data/org0-ca-cert.pem
      - FABRIC_CA_SERVER_DEBUG=true
      - BOOTSTRAP_USER_PASS=ica-org0-admin:adminpw
      - PARENT_URL=https://rca-org0-admin:adminpw@rca-org0:7054
      - TARGET_CHAINFILE=/data/org0-ca-chain.pem
      - ORG=org0
      - FABRIC_ORGS=org0 org1
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=mynet
      - MYSQL_SERVER_HOME = icamariadb-org0
    ports:
      - 7055:7054
    command: /bin/bash -c '/scripts/start-ica-org0.sh 2>&1'
    depends_on:
      - icamariadb-org0
    volumes:
      - ./scripts:/scripts
      - ./data:/data
    networks:
      default:
    restart: always

  rcamariadb-org1:
    image: mariadb:10
    container_name: rcamariadb-org1
    hostname: rcamariadb-org1
    environment:
      - MYSQL_ROOT_PASSWORD=qawsedrf
    ports:
      - 3308:3306
    networks:
      default:
    restart: always

  rca-org1:
    image: hyperledger/fabric-ca:x86_64-1.1.0
    container_name: rca-org1
    hostname: rca-org1
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_CA_NAME=rca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=rca-org1
      - FABRIC_CA_SERVER_CSR_HOSTS=rca-org1
      - FABRIC_CA_SERVER_DEBUG=true
      - BOOTSTRAP_USER_PASS=rca-org1-admin:adminpw
      - TARGET_CERTFILE=/data/org1-ca-cert.pem
      - FABRIC_ORGS=org0 org1
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=mynet
      - MYSQL_SERVER_NAME = rcamariadb-org1
    ports:
      - 7056:7054
    command: /bin/bash -c '/scripts/start-rca-org1.sh 2>&1'
    depends_on:
      - rcamariadb-org1
    volumes:
      - ./scripts:/scripts
      - ./data:/data
    networks:
      default:
    restart: always

  icamariadb-org1:
    image: mariadb:10
    container_name: icamariadb-org1
    hostname: icamariadb-org1
    environment:
      - MYSQL_ROOT_PASSWORD=qawsedrf
    ports:
      - 3309:3306
    networks:
      default:
    restart: always

  ica-org1:
    image: hyperledger/fabric-ca:x86_64-1.1.0
    container_name: ica-org1
    hostname: ica-org1
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_CA_NAME=ica-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=ica-org1
      - FABRIC_CA_SERVER_CSR_HOSTS=ica-org1
      - FABRIC_CA_SERVER_INTERMEDIATE_TLS_CERTFILES=/data/org1-ca-cert.pem
      - FABRIC_CA_SERVER_DEBUG=true
      - BOOTSTRAP_USER_PASS=ica-org1-admin:adminpw
      - PARENT_URL=https://rca-org1-admin:adminpw@rca-org1:7054
      - TARGET_CHAINFILE=/data/org1-ca-chain.pem
      - ORG=org1
      - FABRIC_ORGS=org0 org1
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=mynet
      - MYSQL_SERVER_NAME = icamariadb-org1
    ports:
      - 7057:7054
    command: /bin/bash -c '/scripts/start-ica-org1.sh 2>&1'
    depends_on:
      - icamariadb-org1
    volumes:
      - ./scripts:/scripts
      - ./data:/data
    networks:
      default:
    restart: always
